---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(naniar)
library(visdat)
library(gt)
library(gtExtras)
library(glue)
library(svglite)
library(sf)
library(rnaturalearth)
library(showtext)


```



```{r}
numbats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-07/numbats.csv')

```



```{r}
# look at the missing data
vis_dat(numbats )
```


```{r}
# plot the data by year
numbats |>
  group_by(year) |>
  count() |>
  ggplot(aes(x=year , y=n)) +
  geom_point()
```


```{r}
# function that will return html formatted bar chart
bar_chart <- function(value, color = "red", display_value = '&nbsp;'){
  
  vals <- value/2
  
  # html of two spans with bar chart
  glue::glue('<span style=\"display: inline-block; direction: ltr; border-radius: 4px; ' , 
             ' padding-right: 2px; background-color: {color}; color: {color}; width: {vals} \">&nbsp;</span> ' , 
             '<span style=\" font-weight: bold; display: fixed;\">{display_value}</span>')
}
```



```{r}
numbats_agg <- numbats |>
  group_by(dataResourceName) |>
  summarise(Total=n() , yr_na = sum(is.na(year)) , .groups = 'drop')

science_agg <- numbats |>
  group_by(dataResourceName , scientificName) |>
  summarise(n=n() , .groups = 'drop') |>
  pivot_wider(names_from = scientificName , values_from = n)




nrecords <- nrow(numbats)
yr_na <- sum(is.na(numbats$year))
yr_na_percent <-round(  (yr_na / nrecords)*100 , 0)

```





```{r}
oceania <- ne_countries(type="countries",continent = "oceania",returnclass = "sf") |>
  filter(sovereignt == "Australia")

numbats_sf <- numbats |>
  filter(!is.na(decimalLongitude) ,!is.na(decimalLatitude) ) |>
  st_as_sf( coords=c("decimalLongitude","decimalLatitude")) |>
  st_set_crs(st_crs(oceania))


oceania %>% 
  ggplot() + 
  geom_sf( size=1, color="black") +
  geom_sf(data=numbats_sf , aes(size=2) ,  show.legend = FALSE) +
  coord_sf(xlim = c(114,153), ylim = c(-40,-13))+
  facet_wrap(~dataResourceName , ncol = 4 ) +
  theme_void() +
  theme(plot.background = element_blank(),
        panel.background = element_blank())
```




```{r}

map_plt <- function(name) {
  plt_dat <- numbats |> filter(dataResourceName == name)

  out_plt <- plt_dat |>
    filter(!is.na(decimalLongitude) ,!is.na(decimalLatitude) ) |>
    st_as_sf( coords=c("decimalLongitude","decimalLatitude")) |>
    st_set_crs(st_crs(oceania)) |>
    ggplot() +
    geom_sf(data=oceania, size=1, color="black") +
    geom_sf(aes(size=1.5) ,  show.legend = FALSE) +
    coord_sf(xlim = c(114,153), ylim = c(-40,-13))+
    theme_void() +
    theme(plot.background = element_blank(),
          panel.background = element_blank())

#out

trim = FALSE

out_name <- file.path( tempfile(pattern = "file", tmpdir = tempdir(), fileext = ".svg"))

ggsave( out_name, plot = out_plt, dpi = 25.4 )

on.exit(file.remove(out_name), add = TRUE)

img_plot <- out_name %>%
      readLines() %>%
      paste0(collapse = "") %>%
      gt::html()

#mapply(plot_fn_spark, trim, list_data_in, SIMPLIFY = FALSE)

img_plot
  
}

```



```{r}
map_plt('Western Australian Museum provider for OZCAM')
```




```{r}
numbat_map <- numbats |>
  group_by(dataResourceName) |>
  mutate(mapp = map_plt(dataResourceName)) |>
  select(dataResourceName , mapp) |>
  unique()
```




```{r}
oceania <- ne_countries(type="countries",continent = "oceania",returnclass = "sf") |>
  filter(sovereignt == "Australia")


gt_plt_map <- function(gt_object,
                        column,
                        type = "density",
                        fig_dim = c(5, 30),
                        line_color = "black",
                        fill_color = "grey",
                        bw = NULL,
                        trim = FALSE,
                        same_limit = TRUE) {
  #is_gt_stop(gt_object)
  
  # convert tidyeval column to bare string
  col_bare <- dplyr::select(gt_object[["_data"]], {{ column }}) %>% names()
  
  # segment data with bare string column name
  list_data_in <- gt_index(gt_object, col_bare, as_vector = TRUE)
  
  # convert to a single vector
  data_in <- unlist(list_data_in)
  
  #stopifnot("Specified column must contain list of values" = any(class(list_data_in) %in% "list"))
  #stopifnot("Specified column must be numeric" = is.numeric(data_in))
  #stopifnot("You must indicate the `type` of plot as one of 'boxplot', 'histogram', 'rug_strip' or 'density'." = isTRUE(type %in% c("boxplot", "rug_strip", "histogram", "density")))
  
  # range to be used for plotting if same axis
  #total_rng <- grDevices::extendrange(data_in, r = range(data_in, na.rm = TRUE), f = 0.02)
  
  plot_fn_spark <- function(trim , list_data_in) {
    
    vals <- as.character(stats::na.omit(list_data_in))
    
    input_data <- dplyr::tibble(
      x = 1:length(vals),
      y = vals
    )
    
    plt_dat <- numbats |> filter(dataResourceName == input_data$y)

    plot_out <- plt_dat |>
      filter(!is.na(decimalLongitude) ,!is.na(decimalLatitude) ) |>
      st_as_sf( coords=c("decimalLongitude","decimalLatitude")) |>
      st_set_crs(st_crs(oceania)) |>
      ggplot() +
      geom_sf(data=oceania, color="black") + # oceania map
      geom_sf(  show.legend = FALSE) + # plot points
      coord_sf(xlim = c(114,153), ylim = c(-40,-13))+
      theme_void() +
      theme(plot.background = element_blank(), panel.background = element_blank())
    
    out_name <- file.path(tempfile(pattern = "file", tmpdir = tempdir(), fileext = ".svg") )
    
    ggsave( out_name, plot = plot_out, dpi = 25.4, height = fig_dim[1], width = fig_dim[2], units = "mm")
    
    img_plot <- out_name %>%
      readLines() %>%
      paste0(collapse = "") %>%
      gt::html()
    
    on.exit(file.remove(out_name), add = TRUE)
    
    img_plot
  } # end of plot_fn_spark
  
  text_transform(
    gt_object,
    locations = cells_body(columns = {{ column }}),
    fn = function(x) {
      mapply(plot_fn_spark, trim, list_data_in ,  SIMPLIFY = FALSE)
    }
  )
}
```







```{r}


tbl <- numbats |>
  mutate(yr = case_when(year < 2005 ~ '<05' , 
                        is.na(year) ~ 'Missing' , 
                        .default = substr(year, 3,4) )
         ) |>
  group_by(dataResourceName  , yr) |>
  summarize(n=n() , .groups = 'drop') |>
  arrange(yr) |>
  pivot_wider(names_from = yr, values_from = n) |>
  left_join(numbats_agg , by=c('dataResourceName')) |>
  left_join(science_agg , by='dataResourceName' ) |>
  mutate(bar_chart = bar_chart(Total, color = "dodgerblue" , display_value = Total ),
        bar_chart = map(bar_chart, ~gt::html(as.character(.x))) ) |>
  arrange(desc(Total)) |>
  select(1,bar_chart , c(20,19) , c(2:18) , c(22,23) ) |>
  mutate(Missing = ifelse(is.na(Missing) , 0 , Missing)) |>
  gt() |>
  #cols_width(dataResourceName ~ px(600) , bar_chart~px(200) )  |>
  tab_spanner( label = md("**YEAR**"), columns = c(3:21) ) |>
  tab_spanner( label = md("**Myrmecobius Fasciatus**"), columns = c(22,23 ) ) |>
  sub_missing(columns = c(3:21), missing_text = "" ) |>
  sub_missing(columns = c(22,23 ), missing_text = "0" ) |>
  cols_label(`Myrmecobius fasciatus` = "-" , `Myrmecobius fasciatus rufus` = "Rufus" ) |>
  data_color(columns = Missing, apply_to = 'fill', 
             colors = scales::col_numeric(
                      palette = c("#C2D3CD", "#34435E"),
                      domain = c(0, 300)
             ) ) |>
  cols_align(align = "left" , columns = c(bar_chart)) |>
  cols_align(align = 'center' , columns = c(3:21) )  |>
  cols_align(align = 'right' , columns = c(1) )  |>
  tab_header(title = md("**Numbat Sightings in Australia**") , 
             subtitle = md('subtitle_txt')) |>
  tab_source_note(
    source_note = md("<b>Data: </b>Atlas of Living Australia (tidytuesday) | <b>Table: </b> Nat Rivera @Itsnatrivera")
  ) 

tbl
```




```{r}
tbl_title <- str_glue('**Numbat Sightings in Australia**')
tbl_subtitle <- str_glue('***{yr_na_percent}%*** ({yr_na}/{nrecords}) of the data is missing timespamps with most comming from Western Australian Museum provider for OZCAM')
tbl_caption <- str_glue('<b>Data: </b>Atlas of Living Australia (tidytuesday) | <b>Table: </b> Nat Rivera @Itsnatrivera')

tbl <- numbats |>
  mutate( year = ifelse(year < 2006 , 2005 , year)) |>
  group_by(dataResourceName  ) |>
  summarize(yr_dist=list(year) , .groups = 'drop') |>
  mutate(resource = dataResourceName) |>
  left_join(numbats_agg , by=c('dataResourceName')) |>
  left_join(science_agg , by='dataResourceName' ) |>
  mutate(bar_chart = bar_chart(Total, color = "#F6AE2D" , display_value = Total ),
        bar_chart = map(bar_chart, ~gt::html(as.character(.x))) ) |>
  arrange(desc(Total)) |>
  select(c(1,3,8,2,5,6,7)) |>
  gt() |>
  gt_plt_dist(yr_dist  , fig_dim = c(5, 70) , fill_color = "#1E96FC") |>
  gt_plt_map(column = resource , fig_dim = c(5,22)) |>
  tab_spanner( label = md("**Myrmecobius Fasciatus**"), columns = c(6,7) ) |>
  tab_spanner( label = md("**Year**"), columns = c(4,5) ) |>
  tab_spanner( label = md("**Data Resource**"), columns = c(1,2,3) ) |>
  cols_align(align = "left" , columns = c(bar_chart)) |>
  cols_align(align = 'right' , columns = c(1) )  |>
  cols_width(bar_chart~px(200)  )  |>
  sub_missing(columns = c(6,7), missing_text = "0" ) |>
  cols_label(`Myrmecobius fasciatus` = "-" , 
             `Myrmecobius fasciatus rufus` = "Rufus"  ,
             yr_dist = '<05  06  08  10  12  14  16  18  20  22' , 
             yr_na = 'Missing' , bar_chart = 'Total' , dataResourceName = 'Name' , resource = 'Map' ) |>
  data_color(columns = yr_na, apply_to = 'fill', 
             colors = scales::col_numeric(
                      palette = c("#C2D3CD", "#34435E"),
                      domain = c(0, 190)
             ) ) |>
  tab_header(title = md(tbl_title) , subtitle = md(tbl_subtitle)) |>
  tab_source_note(source_note = md(tbl_caption) ) 



tbl
```




