---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(tidytext)
library(wordcloud2)
library(stopwords)
library(BobRossColors)
library(RColorBrewer)
library(ggimage)
library(ggtext)

theme_set(theme_minimal())
```




```{r}
bob_ross <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-02-21/bob_ross.csv')

# source for bob ross image
# https://www.pngfind.com/download/iwiimTJ_bobross-freetoedit-bob-ross-hd-png-download/

```





```{r}

stops <-stopwords("en") %>% as.data.frame()

words <-  bob_ross %>%
  select(painting_title) %>%
  unnest_tokens(word, painting_title) %>% 
  count(word, sort=TRUE) %>% 
  anti_join(stops , by=c('word'='.'))


bob_colors <- unique_bob_ross_colors$color_hex 
bob_colors <- bob_colors[! bob_colors %in% c('#FFFFFF')]

cloud <- wordcloud2(words 
                    ,minSize=0.5
                    ,size=1
                    #, backgroundColor = 'black' 
                    , minRotation = 0
                    , maxRotation = 0
                    , color=bob_colors
                    ,figPath='bob-ross-afro_2.jpg' 
                    #, shape='star'
                    )
cloud
```







```{r}
bar_ross <- words %>% 
  filter(n>=10) %>% 
  arrange(desc(n)) %>% 
  ggplot(aes(x=n , y=reorder(word , n) , label=paste0(word,'-',n))) +
  geom_bar(stat = 'identity' , fill=bob_colors[12]) +
  geom_text(x=1  , hjust = 0) +
  labs(title="Most Common Words in Bob Ross' Titles" , 
       caption='**Data:** #TidyTuesday  **Plot:** @itsnatrivera') +
  theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.caption = element_markdown()
    )


blank <- ggplot() + theme_void()

plts <- ggarrange(bar_ross , blank , blank , blank , heights = c(20,2) , widths = c(4,6))

ross_plt <- ggbackground(plts, 'bob_ross_cloud.png')
ross_plt
```




